use async_trait::async_trait;
use std::collections::HashMap;

/// Static metadata — generated by `#[derive(Command)]`.
pub trait CommandMeta {
    fn command_name()        -> &'static str;
    fn command_description() -> &'static str { "" }
}

/// The executable command trait.
#[async_trait]
pub trait Command: CommandMeta + Send + Sync {
    async fn handle(&self, args: &Args) -> anyhow::Result<()>;
}

/// Parsed CLI arguments and options.
#[derive(Debug, Default, Clone)]
pub struct Args {
    pub positional: Vec<String>,
    pub options: HashMap<String, String>,
    pub flags: Vec<String>,
}

impl Args {
    pub fn parse(raw: &[String]) -> Self {
        let mut args = Args::default();
        let mut i = 0;
        while i < raw.len() {
            let token = &raw[i];
            if token.starts_with("--") {
                let key = token.trim_start_matches('-');
                if let Some(eq) = key.find('=') {
                    args.options.insert(key[..eq].to_string(), key[eq + 1..].to_string());
                } else if i + 1 < raw.len() && !raw[i + 1].starts_with('-') {
                    i += 1;
                    args.options.insert(key.to_string(), raw[i].clone());
                } else {
                    args.flags.push(key.to_string());
                }
            } else if token.starts_with('-') {
                args.flags.push(token.trim_start_matches('-').to_string());
            } else {
                args.positional.push(token.clone());
            }
            i += 1;
        }
        args
    }

    pub fn get(&self, key: &str) -> Option<&str> {
        self.options.get(key).map(|s| s.as_str())
    }

    pub fn flag(&self, key: &str) -> bool {
        self.flags.contains(&key.to_string())
    }

    pub fn argument(&self, index: usize) -> Option<&str> {
        self.positional.get(index).map(|s| s.as_str())
    }
}
