use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use std::fmt;

/// Static metadata for a job struct — generated by `#[derive(Job)]`.
pub trait JobMeta {
    fn queue_name() -> &'static str { "default" }
    fn max_tries()  -> u32 { 3 }
    fn timeout_secs() -> u64 { 60 }
}

/// The executable job trait.
#[async_trait]
pub trait Job: JobMeta + Serialize + for<'de> Deserialize<'de> + Send + Sync + 'static {
    /// Execute the job.  Return `Ok(())` to mark success, `Err` to mark failure.
    async fn handle(&self) -> anyhow::Result<()>;

    /// Called when the job has failed all retries.
    async fn failed(&self, error: &str) {
        tracing::error!(
            job = std::any::type_name::<Self>(),
            "Job failed after max tries: {}", error
        );
    }

    fn serialize_payload(&self) -> serde_json::Result<String> {
        serde_json::to_string(self)
    }
}

/// An envelope stored in the queue backend.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobPayload {
    pub id: String,
    pub queue: String,
    pub job_class: String,
    pub payload: String,
    pub attempts: u32,
    pub max_tries: u32,
    pub timeout_secs: u64,
    pub available_at: i64,
    pub created_at: i64,
}

impl JobPayload {
    pub fn new<J: Job>(job: &J) -> serde_json::Result<Self> {
        Ok(Self {
            id: uuid::Uuid::new_v4().to_string(),
            queue: J::queue_name().to_string(),
            job_class: std::any::type_name::<J>().to_string(),
            payload: job.serialize_payload()?,
            attempts: 0,
            max_tries: J::max_tries(),
            timeout_secs: J::timeout_secs(),
            available_at: chrono::Utc::now().timestamp(),
            created_at: chrono::Utc::now().timestamp(),
        })
    }
}
